### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by aleemont1** [progetto-oop-22-23/OOP22-HOMER#151]
Sorry for being late.
TODO:

- [x] A/C and heating implement PoweredDevice
- [x] Start first simulation ASAP
- [x] View
- [x] Graphs for electrical consumption
- [x] Logger
- [x] Scheduler
- [x] remove device button
- [x] use slider on window, door and blinds
